import { CreateUserFromGoogleData, CreateUserFromGoogleVariables, SetUserTypeData, SetUserTypeVariables, CreateTimeEntryData, CreateTimeEntryVariables, CreateWorkLogOnlyData, CreateWorkLogOnlyVariables, UpdateTimeEntryData, UpdateTimeEntryVariables, UpdateTimeEntryClearTicketData, UpdateTimeEntryClearTicketVariables, DeleteTimeEntryData, DeleteTimeEntryVariables, UpsertTicketData, UpsertTicketVariables, UpdateTicketData, UpdateTicketVariables, SelectMyColorSchemeData, SelectMyColorSchemeVariables, ClearMyColorSchemeData, SelectMyPerformanceModeData, SelectMyPerformanceModeVariables, SelectMyBackgroundOpacityData, SelectMyBackgroundOpacityVariables, SelectMyExternalTicketLinkTemplateData, SelectMyExternalTicketLinkTemplateVariables, SelectMyCardStyleData, SelectMyCardStyleVariables, SelectMyBordersEnabledData, SelectMyBordersEnabledVariables, SelectMyTicketColorsEnabledData, SelectMyTicketColorsEnabledVariables, UpdateWorkLogData, UpdateWorkLogVariables, DeleteWorkLogData, DeleteWorkLogVariables, RestoreWorkLogData, RestoreWorkLogVariables, CreateWorkLogData, CreateWorkLogVariables, UpsertGoogleCalendarConnectionData, UpsertGoogleCalendarConnectionVariables, UpdateGoogleCalendarSyncPrefsData, UpdateGoogleCalendarSyncPrefsVariables, TouchGoogleCalendarLastSyncedData, TouchGoogleCalendarLastSyncedVariables, DeleteGoogleCalendarConnectionData, DeleteGoogleCalendarConnectionVariables, ListUsersData, GetMyUserData, ListColorSchemesData, ListTicketsData, ListTicketsVariables, ListTimeEntriesData, ListTimeEntriesVariables, GetTimeEntryData, GetTimeEntryVariables, ListWorkLogsData, ListWorkLogsVariables, ListTimeEntriesByWorkLogData, ListTimeEntriesByWorkLogVariables, ListTimeEntriesByTicketData, ListTimeEntriesByTicketVariables, ListMyTimeEntriesData, ListMyTimeEntriesVariables, ListTimeEntriesByDateRangeData, ListTimeEntriesByDateRangeVariables, ListUserTypesData, GetUserAccessByGoogleUidData, GetUserAccessByGoogleUidVariables, AdminListUsersData, AdminListUserTypesData, AdminListFeaturesData, AdminGetUserData, AdminGetUserVariables, AdminListTeamsData, GetGoogleCalendarConnectionData, GetGoogleCalendarConnectionVariables } from '../';
import { UseDataConnectQueryResult, useDataConnectQueryOptions, UseDataConnectMutationResult, useDataConnectMutationOptions} from '@tanstack-query-firebase/react/data-connect';
import { UseQueryResult, UseMutationResult} from '@tanstack/react-query';
import { DataConnect } from 'firebase/data-connect';
import { FirebaseError } from 'firebase/app';


export function useCreateUserFromGoogle(options?: useDataConnectMutationOptions<CreateUserFromGoogleData, FirebaseError, CreateUserFromGoogleVariables>): UseDataConnectMutationResult<CreateUserFromGoogleData, CreateUserFromGoogleVariables>;
export function useCreateUserFromGoogle(dc: DataConnect, options?: useDataConnectMutationOptions<CreateUserFromGoogleData, FirebaseError, CreateUserFromGoogleVariables>): UseDataConnectMutationResult<CreateUserFromGoogleData, CreateUserFromGoogleVariables>;

export function useSetUserType(options?: useDataConnectMutationOptions<SetUserTypeData, FirebaseError, SetUserTypeVariables>): UseDataConnectMutationResult<SetUserTypeData, SetUserTypeVariables>;
export function useSetUserType(dc: DataConnect, options?: useDataConnectMutationOptions<SetUserTypeData, FirebaseError, SetUserTypeVariables>): UseDataConnectMutationResult<SetUserTypeData, SetUserTypeVariables>;

export function useCreateTimeEntry(options?: useDataConnectMutationOptions<CreateTimeEntryData, FirebaseError, CreateTimeEntryVariables>): UseDataConnectMutationResult<CreateTimeEntryData, CreateTimeEntryVariables>;
export function useCreateTimeEntry(dc: DataConnect, options?: useDataConnectMutationOptions<CreateTimeEntryData, FirebaseError, CreateTimeEntryVariables>): UseDataConnectMutationResult<CreateTimeEntryData, CreateTimeEntryVariables>;

export function useCreateWorkLogOnly(options?: useDataConnectMutationOptions<CreateWorkLogOnlyData, FirebaseError, CreateWorkLogOnlyVariables>): UseDataConnectMutationResult<CreateWorkLogOnlyData, CreateWorkLogOnlyVariables>;
export function useCreateWorkLogOnly(dc: DataConnect, options?: useDataConnectMutationOptions<CreateWorkLogOnlyData, FirebaseError, CreateWorkLogOnlyVariables>): UseDataConnectMutationResult<CreateWorkLogOnlyData, CreateWorkLogOnlyVariables>;

export function useUpdateTimeEntry(options?: useDataConnectMutationOptions<UpdateTimeEntryData, FirebaseError, UpdateTimeEntryVariables>): UseDataConnectMutationResult<UpdateTimeEntryData, UpdateTimeEntryVariables>;
export function useUpdateTimeEntry(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateTimeEntryData, FirebaseError, UpdateTimeEntryVariables>): UseDataConnectMutationResult<UpdateTimeEntryData, UpdateTimeEntryVariables>;

export function useUpdateTimeEntryClearTicket(options?: useDataConnectMutationOptions<UpdateTimeEntryClearTicketData, FirebaseError, UpdateTimeEntryClearTicketVariables>): UseDataConnectMutationResult<UpdateTimeEntryClearTicketData, UpdateTimeEntryClearTicketVariables>;
export function useUpdateTimeEntryClearTicket(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateTimeEntryClearTicketData, FirebaseError, UpdateTimeEntryClearTicketVariables>): UseDataConnectMutationResult<UpdateTimeEntryClearTicketData, UpdateTimeEntryClearTicketVariables>;

export function useDeleteTimeEntry(options?: useDataConnectMutationOptions<DeleteTimeEntryData, FirebaseError, DeleteTimeEntryVariables>): UseDataConnectMutationResult<DeleteTimeEntryData, DeleteTimeEntryVariables>;
export function useDeleteTimeEntry(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteTimeEntryData, FirebaseError, DeleteTimeEntryVariables>): UseDataConnectMutationResult<DeleteTimeEntryData, DeleteTimeEntryVariables>;

export function useUpsertTicket(options?: useDataConnectMutationOptions<UpsertTicketData, FirebaseError, UpsertTicketVariables>): UseDataConnectMutationResult<UpsertTicketData, UpsertTicketVariables>;
export function useUpsertTicket(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertTicketData, FirebaseError, UpsertTicketVariables>): UseDataConnectMutationResult<UpsertTicketData, UpsertTicketVariables>;

export function useUpdateTicket(options?: useDataConnectMutationOptions<UpdateTicketData, FirebaseError, UpdateTicketVariables>): UseDataConnectMutationResult<UpdateTicketData, UpdateTicketVariables>;
export function useUpdateTicket(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateTicketData, FirebaseError, UpdateTicketVariables>): UseDataConnectMutationResult<UpdateTicketData, UpdateTicketVariables>;

export function useSelectMyColorScheme(options?: useDataConnectMutationOptions<SelectMyColorSchemeData, FirebaseError, SelectMyColorSchemeVariables>): UseDataConnectMutationResult<SelectMyColorSchemeData, SelectMyColorSchemeVariables>;
export function useSelectMyColorScheme(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyColorSchemeData, FirebaseError, SelectMyColorSchemeVariables>): UseDataConnectMutationResult<SelectMyColorSchemeData, SelectMyColorSchemeVariables>;

export function useClearMyColorScheme(options?: useDataConnectMutationOptions<ClearMyColorSchemeData, FirebaseError, void>): UseDataConnectMutationResult<ClearMyColorSchemeData, undefined>;
export function useClearMyColorScheme(dc: DataConnect, options?: useDataConnectMutationOptions<ClearMyColorSchemeData, FirebaseError, void>): UseDataConnectMutationResult<ClearMyColorSchemeData, undefined>;

export function useSelectMyPerformanceMode(options?: useDataConnectMutationOptions<SelectMyPerformanceModeData, FirebaseError, SelectMyPerformanceModeVariables>): UseDataConnectMutationResult<SelectMyPerformanceModeData, SelectMyPerformanceModeVariables>;
export function useSelectMyPerformanceMode(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyPerformanceModeData, FirebaseError, SelectMyPerformanceModeVariables>): UseDataConnectMutationResult<SelectMyPerformanceModeData, SelectMyPerformanceModeVariables>;

export function useSelectMyBackgroundOpacity(options?: useDataConnectMutationOptions<SelectMyBackgroundOpacityData, FirebaseError, SelectMyBackgroundOpacityVariables>): UseDataConnectMutationResult<SelectMyBackgroundOpacityData, SelectMyBackgroundOpacityVariables>;
export function useSelectMyBackgroundOpacity(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyBackgroundOpacityData, FirebaseError, SelectMyBackgroundOpacityVariables>): UseDataConnectMutationResult<SelectMyBackgroundOpacityData, SelectMyBackgroundOpacityVariables>;

export function useSelectMyExternalTicketLinkTemplate(options?: useDataConnectMutationOptions<SelectMyExternalTicketLinkTemplateData, FirebaseError, SelectMyExternalTicketLinkTemplateVariables | void>): UseDataConnectMutationResult<SelectMyExternalTicketLinkTemplateData, SelectMyExternalTicketLinkTemplateVariables>;
export function useSelectMyExternalTicketLinkTemplate(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyExternalTicketLinkTemplateData, FirebaseError, SelectMyExternalTicketLinkTemplateVariables | void>): UseDataConnectMutationResult<SelectMyExternalTicketLinkTemplateData, SelectMyExternalTicketLinkTemplateVariables>;

export function useSelectMyCardStyle(options?: useDataConnectMutationOptions<SelectMyCardStyleData, FirebaseError, SelectMyCardStyleVariables>): UseDataConnectMutationResult<SelectMyCardStyleData, SelectMyCardStyleVariables>;
export function useSelectMyCardStyle(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyCardStyleData, FirebaseError, SelectMyCardStyleVariables>): UseDataConnectMutationResult<SelectMyCardStyleData, SelectMyCardStyleVariables>;

export function useSelectMyBordersEnabled(options?: useDataConnectMutationOptions<SelectMyBordersEnabledData, FirebaseError, SelectMyBordersEnabledVariables>): UseDataConnectMutationResult<SelectMyBordersEnabledData, SelectMyBordersEnabledVariables>;
export function useSelectMyBordersEnabled(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyBordersEnabledData, FirebaseError, SelectMyBordersEnabledVariables>): UseDataConnectMutationResult<SelectMyBordersEnabledData, SelectMyBordersEnabledVariables>;

export function useSelectMyTicketColorsEnabled(options?: useDataConnectMutationOptions<SelectMyTicketColorsEnabledData, FirebaseError, SelectMyTicketColorsEnabledVariables>): UseDataConnectMutationResult<SelectMyTicketColorsEnabledData, SelectMyTicketColorsEnabledVariables>;
export function useSelectMyTicketColorsEnabled(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyTicketColorsEnabledData, FirebaseError, SelectMyTicketColorsEnabledVariables>): UseDataConnectMutationResult<SelectMyTicketColorsEnabledData, SelectMyTicketColorsEnabledVariables>;

export function useUpdateWorkLog(options?: useDataConnectMutationOptions<UpdateWorkLogData, FirebaseError, UpdateWorkLogVariables>): UseDataConnectMutationResult<UpdateWorkLogData, UpdateWorkLogVariables>;
export function useUpdateWorkLog(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateWorkLogData, FirebaseError, UpdateWorkLogVariables>): UseDataConnectMutationResult<UpdateWorkLogData, UpdateWorkLogVariables>;

export function useDeleteWorkLog(options?: useDataConnectMutationOptions<DeleteWorkLogData, FirebaseError, DeleteWorkLogVariables>): UseDataConnectMutationResult<DeleteWorkLogData, DeleteWorkLogVariables>;
export function useDeleteWorkLog(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteWorkLogData, FirebaseError, DeleteWorkLogVariables>): UseDataConnectMutationResult<DeleteWorkLogData, DeleteWorkLogVariables>;

export function useRestoreWorkLog(options?: useDataConnectMutationOptions<RestoreWorkLogData, FirebaseError, RestoreWorkLogVariables>): UseDataConnectMutationResult<RestoreWorkLogData, RestoreWorkLogVariables>;
export function useRestoreWorkLog(dc: DataConnect, options?: useDataConnectMutationOptions<RestoreWorkLogData, FirebaseError, RestoreWorkLogVariables>): UseDataConnectMutationResult<RestoreWorkLogData, RestoreWorkLogVariables>;

export function useCreateWorkLog(options?: useDataConnectMutationOptions<CreateWorkLogData, FirebaseError, CreateWorkLogVariables>): UseDataConnectMutationResult<CreateWorkLogData, CreateWorkLogVariables>;
export function useCreateWorkLog(dc: DataConnect, options?: useDataConnectMutationOptions<CreateWorkLogData, FirebaseError, CreateWorkLogVariables>): UseDataConnectMutationResult<CreateWorkLogData, CreateWorkLogVariables>;

export function useUpsertGoogleCalendarConnection(options?: useDataConnectMutationOptions<UpsertGoogleCalendarConnectionData, FirebaseError, UpsertGoogleCalendarConnectionVariables>): UseDataConnectMutationResult<UpsertGoogleCalendarConnectionData, UpsertGoogleCalendarConnectionVariables>;
export function useUpsertGoogleCalendarConnection(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertGoogleCalendarConnectionData, FirebaseError, UpsertGoogleCalendarConnectionVariables>): UseDataConnectMutationResult<UpsertGoogleCalendarConnectionData, UpsertGoogleCalendarConnectionVariables>;

export function useUpdateGoogleCalendarSyncPrefs(options?: useDataConnectMutationOptions<UpdateGoogleCalendarSyncPrefsData, FirebaseError, UpdateGoogleCalendarSyncPrefsVariables>): UseDataConnectMutationResult<UpdateGoogleCalendarSyncPrefsData, UpdateGoogleCalendarSyncPrefsVariables>;
export function useUpdateGoogleCalendarSyncPrefs(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateGoogleCalendarSyncPrefsData, FirebaseError, UpdateGoogleCalendarSyncPrefsVariables>): UseDataConnectMutationResult<UpdateGoogleCalendarSyncPrefsData, UpdateGoogleCalendarSyncPrefsVariables>;

export function useTouchGoogleCalendarLastSynced(options?: useDataConnectMutationOptions<TouchGoogleCalendarLastSyncedData, FirebaseError, TouchGoogleCalendarLastSyncedVariables>): UseDataConnectMutationResult<TouchGoogleCalendarLastSyncedData, TouchGoogleCalendarLastSyncedVariables>;
export function useTouchGoogleCalendarLastSynced(dc: DataConnect, options?: useDataConnectMutationOptions<TouchGoogleCalendarLastSyncedData, FirebaseError, TouchGoogleCalendarLastSyncedVariables>): UseDataConnectMutationResult<TouchGoogleCalendarLastSyncedData, TouchGoogleCalendarLastSyncedVariables>;

export function useDeleteGoogleCalendarConnection(options?: useDataConnectMutationOptions<DeleteGoogleCalendarConnectionData, FirebaseError, DeleteGoogleCalendarConnectionVariables>): UseDataConnectMutationResult<DeleteGoogleCalendarConnectionData, DeleteGoogleCalendarConnectionVariables>;
export function useDeleteGoogleCalendarConnection(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteGoogleCalendarConnectionData, FirebaseError, DeleteGoogleCalendarConnectionVariables>): UseDataConnectMutationResult<DeleteGoogleCalendarConnectionData, DeleteGoogleCalendarConnectionVariables>;

export function useListUsers(options?: useDataConnectQueryOptions<ListUsersData>): UseDataConnectQueryResult<ListUsersData, undefined>;
export function useListUsers(dc: DataConnect, options?: useDataConnectQueryOptions<ListUsersData>): UseDataConnectQueryResult<ListUsersData, undefined>;

export function useGetMyUser(options?: useDataConnectQueryOptions<GetMyUserData>): UseDataConnectQueryResult<GetMyUserData, undefined>;
export function useGetMyUser(dc: DataConnect, options?: useDataConnectQueryOptions<GetMyUserData>): UseDataConnectQueryResult<GetMyUserData, undefined>;

export function useListColorSchemes(options?: useDataConnectQueryOptions<ListColorSchemesData>): UseDataConnectQueryResult<ListColorSchemesData, undefined>;
export function useListColorSchemes(dc: DataConnect, options?: useDataConnectQueryOptions<ListColorSchemesData>): UseDataConnectQueryResult<ListColorSchemesData, undefined>;

export function useListTickets(vars?: ListTicketsVariables, options?: useDataConnectQueryOptions<ListTicketsData>): UseDataConnectQueryResult<ListTicketsData, ListTicketsVariables>;
export function useListTickets(dc: DataConnect, vars?: ListTicketsVariables, options?: useDataConnectQueryOptions<ListTicketsData>): UseDataConnectQueryResult<ListTicketsData, ListTicketsVariables>;

export function useListTimeEntries(vars: ListTimeEntriesVariables, options?: useDataConnectQueryOptions<ListTimeEntriesData>): UseDataConnectQueryResult<ListTimeEntriesData, ListTimeEntriesVariables>;
export function useListTimeEntries(dc: DataConnect, vars: ListTimeEntriesVariables, options?: useDataConnectQueryOptions<ListTimeEntriesData>): UseDataConnectQueryResult<ListTimeEntriesData, ListTimeEntriesVariables>;

export function useGetTimeEntry(vars: GetTimeEntryVariables, options?: useDataConnectQueryOptions<GetTimeEntryData>): UseDataConnectQueryResult<GetTimeEntryData, GetTimeEntryVariables>;
export function useGetTimeEntry(dc: DataConnect, vars: GetTimeEntryVariables, options?: useDataConnectQueryOptions<GetTimeEntryData>): UseDataConnectQueryResult<GetTimeEntryData, GetTimeEntryVariables>;

export function useListWorkLogs(vars?: ListWorkLogsVariables, options?: useDataConnectQueryOptions<ListWorkLogsData>): UseDataConnectQueryResult<ListWorkLogsData, ListWorkLogsVariables>;
export function useListWorkLogs(dc: DataConnect, vars?: ListWorkLogsVariables, options?: useDataConnectQueryOptions<ListWorkLogsData>): UseDataConnectQueryResult<ListWorkLogsData, ListWorkLogsVariables>;

export function useListTimeEntriesByWorkLog(vars: ListTimeEntriesByWorkLogVariables, options?: useDataConnectQueryOptions<ListTimeEntriesByWorkLogData>): UseDataConnectQueryResult<ListTimeEntriesByWorkLogData, ListTimeEntriesByWorkLogVariables>;
export function useListTimeEntriesByWorkLog(dc: DataConnect, vars: ListTimeEntriesByWorkLogVariables, options?: useDataConnectQueryOptions<ListTimeEntriesByWorkLogData>): UseDataConnectQueryResult<ListTimeEntriesByWorkLogData, ListTimeEntriesByWorkLogVariables>;

export function useListTimeEntriesByTicket(vars: ListTimeEntriesByTicketVariables, options?: useDataConnectQueryOptions<ListTimeEntriesByTicketData>): UseDataConnectQueryResult<ListTimeEntriesByTicketData, ListTimeEntriesByTicketVariables>;
export function useListTimeEntriesByTicket(dc: DataConnect, vars: ListTimeEntriesByTicketVariables, options?: useDataConnectQueryOptions<ListTimeEntriesByTicketData>): UseDataConnectQueryResult<ListTimeEntriesByTicketData, ListTimeEntriesByTicketVariables>;

export function useListMyTimeEntries(vars?: ListMyTimeEntriesVariables, options?: useDataConnectQueryOptions<ListMyTimeEntriesData>): UseDataConnectQueryResult<ListMyTimeEntriesData, ListMyTimeEntriesVariables>;
export function useListMyTimeEntries(dc: DataConnect, vars?: ListMyTimeEntriesVariables, options?: useDataConnectQueryOptions<ListMyTimeEntriesData>): UseDataConnectQueryResult<ListMyTimeEntriesData, ListMyTimeEntriesVariables>;

export function useListTimeEntriesByDateRange(vars: ListTimeEntriesByDateRangeVariables, options?: useDataConnectQueryOptions<ListTimeEntriesByDateRangeData>): UseDataConnectQueryResult<ListTimeEntriesByDateRangeData, ListTimeEntriesByDateRangeVariables>;
export function useListTimeEntriesByDateRange(dc: DataConnect, vars: ListTimeEntriesByDateRangeVariables, options?: useDataConnectQueryOptions<ListTimeEntriesByDateRangeData>): UseDataConnectQueryResult<ListTimeEntriesByDateRangeData, ListTimeEntriesByDateRangeVariables>;

export function useListUserTypes(options?: useDataConnectQueryOptions<ListUserTypesData>): UseDataConnectQueryResult<ListUserTypesData, undefined>;
export function useListUserTypes(dc: DataConnect, options?: useDataConnectQueryOptions<ListUserTypesData>): UseDataConnectQueryResult<ListUserTypesData, undefined>;

export function useGetUserAccessByGoogleUid(vars: GetUserAccessByGoogleUidVariables, options?: useDataConnectQueryOptions<GetUserAccessByGoogleUidData>): UseDataConnectQueryResult<GetUserAccessByGoogleUidData, GetUserAccessByGoogleUidVariables>;
export function useGetUserAccessByGoogleUid(dc: DataConnect, vars: GetUserAccessByGoogleUidVariables, options?: useDataConnectQueryOptions<GetUserAccessByGoogleUidData>): UseDataConnectQueryResult<GetUserAccessByGoogleUidData, GetUserAccessByGoogleUidVariables>;

export function useAdminListUsers(options?: useDataConnectQueryOptions<AdminListUsersData>): UseDataConnectQueryResult<AdminListUsersData, undefined>;
export function useAdminListUsers(dc: DataConnect, options?: useDataConnectQueryOptions<AdminListUsersData>): UseDataConnectQueryResult<AdminListUsersData, undefined>;

export function useAdminListUserTypes(options?: useDataConnectQueryOptions<AdminListUserTypesData>): UseDataConnectQueryResult<AdminListUserTypesData, undefined>;
export function useAdminListUserTypes(dc: DataConnect, options?: useDataConnectQueryOptions<AdminListUserTypesData>): UseDataConnectQueryResult<AdminListUserTypesData, undefined>;

export function useAdminListFeatures(options?: useDataConnectQueryOptions<AdminListFeaturesData>): UseDataConnectQueryResult<AdminListFeaturesData, undefined>;
export function useAdminListFeatures(dc: DataConnect, options?: useDataConnectQueryOptions<AdminListFeaturesData>): UseDataConnectQueryResult<AdminListFeaturesData, undefined>;

export function useAdminGetUser(vars: AdminGetUserVariables, options?: useDataConnectQueryOptions<AdminGetUserData>): UseDataConnectQueryResult<AdminGetUserData, AdminGetUserVariables>;
export function useAdminGetUser(dc: DataConnect, vars: AdminGetUserVariables, options?: useDataConnectQueryOptions<AdminGetUserData>): UseDataConnectQueryResult<AdminGetUserData, AdminGetUserVariables>;

export function useAdminListTeams(options?: useDataConnectQueryOptions<AdminListTeamsData>): UseDataConnectQueryResult<AdminListTeamsData, undefined>;
export function useAdminListTeams(dc: DataConnect, options?: useDataConnectQueryOptions<AdminListTeamsData>): UseDataConnectQueryResult<AdminListTeamsData, undefined>;

export function useGetGoogleCalendarConnection(vars: GetGoogleCalendarConnectionVariables, options?: useDataConnectQueryOptions<GetGoogleCalendarConnectionData>): UseDataConnectQueryResult<GetGoogleCalendarConnectionData, GetGoogleCalendarConnectionVariables>;
export function useGetGoogleCalendarConnection(dc: DataConnect, vars: GetGoogleCalendarConnectionVariables, options?: useDataConnectQueryOptions<GetGoogleCalendarConnectionData>): UseDataConnectQueryResult<GetGoogleCalendarConnectionData, GetGoogleCalendarConnectionVariables>;
