extend type Mutation {
  """
  ✨ Insert a single `ColorScheme` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  colorScheme_insert(
    """
    Data object to insert into the table.
    """
    data: ColorScheme_Data!
  ): ColorScheme_KeyOutput! @fdc_generated(from: "ColorScheme", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Feature` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  feature_insert(
    """
    Data object to insert into the table.
    """
    data: Feature_Data!
  ): Feature_KeyOutput! @fdc_generated(from: "Feature", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Team` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  team_insert(
    """
    Data object to insert into the table.
    """
    data: Team_Data!
  ): Team_KeyOutput! @fdc_generated(from: "Team", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `TeamMember` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  teamMember_insert(
    """
    Data object to insert into the table.
    """
    data: TeamMember_Data!
  ): TeamMember_KeyOutput! @fdc_generated(from: "TeamMember", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Theme` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  theme_insert(
    """
    Data object to insert into the table.
    """
    data: Theme_Data!
  ): Theme_KeyOutput! @fdc_generated(from: "Theme", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Ticket` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  ticket_insert(
    """
    Data object to insert into the table.
    """
    data: Ticket_Data!
  ): Ticket_KeyOutput! @fdc_generated(from: "Ticket", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `TimeEntry` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  timeEntry_insert(
    """
    Data object to insert into the table.
    """
    data: TimeEntry_Data!
  ): TimeEntry_KeyOutput! @fdc_generated(from: "TimeEntry", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserType` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userType_insert(
    """
    Data object to insert into the table.
    """
    data: UserType_Data!
  ): UserType_KeyOutput! @fdc_generated(from: "UserType", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserTypeFeature` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userTypeFeature_insert(
    """
    Data object to insert into the table.
    """
    data: UserTypeFeature_Data!
  ): UserTypeFeature_KeyOutput! @fdc_generated(from: "UserTypeFeature", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `WorkLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workLog_insert(
    """
    Data object to insert into the table.
    """
    data: WorkLog_Data!
  ): WorkLog_KeyOutput! @fdc_generated(from: "WorkLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert `ColorScheme` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  colorScheme_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ColorScheme_Data!]!
  ): [ColorScheme_KeyOutput!]! @fdc_generated(from: "ColorScheme", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Feature` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  feature_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Feature_Data!]!
  ): [Feature_KeyOutput!]! @fdc_generated(from: "Feature", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Team` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  team_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Team_Data!]!
  ): [Team_KeyOutput!]! @fdc_generated(from: "Team", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `TeamMember` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  teamMember_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [TeamMember_Data!]!
  ): [TeamMember_KeyOutput!]! @fdc_generated(from: "TeamMember", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Theme` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  theme_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Theme_Data!]!
  ): [Theme_KeyOutput!]! @fdc_generated(from: "Theme", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Ticket` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  ticket_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Ticket_Data!]!
  ): [Ticket_KeyOutput!]! @fdc_generated(from: "Ticket", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `TimeEntry` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  timeEntry_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [TimeEntry_Data!]!
  ): [TimeEntry_KeyOutput!]! @fdc_generated(from: "TimeEntry", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserType` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userType_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserType_Data!]!
  ): [UserType_KeyOutput!]! @fdc_generated(from: "UserType", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserTypeFeature` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userTypeFeature_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserTypeFeature_Data!]!
  ): [UserTypeFeature_KeyOutput!]! @fdc_generated(from: "UserTypeFeature", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `WorkLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [WorkLog_Data!]!
  ): [WorkLog_KeyOutput!]! @fdc_generated(from: "WorkLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `ColorScheme` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ColorScheme`.
  """
  colorScheme_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ColorScheme_Data!
  ): ColorScheme_KeyOutput! @fdc_generated(from: "ColorScheme", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Feature` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Feature`.
  """
  feature_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Feature_Data!
  ): Feature_KeyOutput! @fdc_generated(from: "Feature", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Team` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Team`.
  """
  team_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Team_Data!
  ): Team_KeyOutput! @fdc_generated(from: "Team", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `TeamMember` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TeamMember`.
  """
  teamMember_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: TeamMember_Data!
  ): TeamMember_KeyOutput! @fdc_generated(from: "TeamMember", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Theme` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Theme`.
  """
  theme_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Theme_Data!
  ): Theme_KeyOutput! @fdc_generated(from: "Theme", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Ticket` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Ticket`.
  """
  ticket_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Ticket_Data!
  ): Ticket_KeyOutput! @fdc_generated(from: "Ticket", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `TimeEntry` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TimeEntry`.
  """
  timeEntry_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: TimeEntry_Data!
  ): TimeEntry_KeyOutput! @fdc_generated(from: "TimeEntry", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserType` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserType`.
  """
  userType_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserType_Data!
  ): UserType_KeyOutput! @fdc_generated(from: "UserType", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserTypeFeature` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserTypeFeature`.
  """
  userTypeFeature_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserTypeFeature_Data!
  ): UserTypeFeature_KeyOutput! @fdc_generated(from: "UserTypeFeature", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `WorkLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorkLog`.
  """
  workLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: WorkLog_Data!
  ): WorkLog_KeyOutput! @fdc_generated(from: "WorkLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `ColorScheme` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ColorScheme`.
  """
  colorScheme_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ColorScheme_Data!]!
  ): [ColorScheme_KeyOutput!]! @fdc_generated(from: "ColorScheme", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Feature` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Feature`.
  """
  feature_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Feature_Data!]!
  ): [Feature_KeyOutput!]! @fdc_generated(from: "Feature", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Team` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Team`.
  """
  team_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Team_Data!]!
  ): [Team_KeyOutput!]! @fdc_generated(from: "Team", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `TeamMember` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TeamMember`.
  """
  teamMember_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [TeamMember_Data!]!
  ): [TeamMember_KeyOutput!]! @fdc_generated(from: "TeamMember", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Theme` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Theme`.
  """
  theme_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Theme_Data!]!
  ): [Theme_KeyOutput!]! @fdc_generated(from: "Theme", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Ticket` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Ticket`.
  """
  ticket_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Ticket_Data!]!
  ): [Ticket_KeyOutput!]! @fdc_generated(from: "Ticket", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `TimeEntry` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TimeEntry`.
  """
  timeEntry_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [TimeEntry_Data!]!
  ): [TimeEntry_KeyOutput!]! @fdc_generated(from: "TimeEntry", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserType` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserType`.
  """
  userType_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserType_Data!]!
  ): [UserType_KeyOutput!]! @fdc_generated(from: "UserType", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserTypeFeature` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserTypeFeature`.
  """
  userTypeFeature_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserTypeFeature_Data!]!
  ): [UserTypeFeature_KeyOutput!]! @fdc_generated(from: "UserTypeFeature", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `WorkLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorkLog`.
  """
  workLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [WorkLog_Data!]!
  ): [WorkLog_KeyOutput!]! @fdc_generated(from: "WorkLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `ColorScheme` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ColorScheme` or `null` if not found.
  """
  colorScheme_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ColorScheme_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ColorScheme_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ColorScheme_Data!
  ): ColorScheme_KeyOutput @fdc_generated(from: "ColorScheme", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Feature` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Feature` or `null` if not found.
  """
  feature_update(
    """
    The key used to identify the object.
    """
    key: Feature_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Feature_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Feature_Data!
  ): Feature_KeyOutput @fdc_generated(from: "Feature", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Team` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Team` or `null` if not found.
  """
  team_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Team_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Team_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Team_Data!
  ): Team_KeyOutput @fdc_generated(from: "Team", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `TeamMember` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `TeamMember` or `null` if not found.
  """
  teamMember_update(
    """
    The key used to identify the object.
    """
    key: TeamMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TeamMember_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: TeamMember_Data!
  ): TeamMember_KeyOutput @fdc_generated(from: "TeamMember", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Theme` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Theme` or `null` if not found.
  """
  theme_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Theme_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Theme_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Theme_Data!
  ): Theme_KeyOutput @fdc_generated(from: "Theme", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Ticket` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Ticket` or `null` if not found.
  """
  ticket_update(
    """
    The key used to identify the object.
    """
    key: Ticket_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Ticket_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Ticket_Data!
  ): Ticket_KeyOutput @fdc_generated(from: "Ticket", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `TimeEntry` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `TimeEntry` or `null` if not found.
  """
  timeEntry_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TimeEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TimeEntry_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: TimeEntry_Data!
  ): TimeEntry_KeyOutput @fdc_generated(from: "TimeEntry", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserType` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserType` or `null` if not found.
  """
  userType_update(
    """
    The key used to identify the object.
    """
    key: UserType_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserType_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserType_Data!
  ): UserType_KeyOutput @fdc_generated(from: "UserType", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserTypeFeature` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserTypeFeature` or `null` if not found.
  """
  userTypeFeature_update(
    """
    The key used to identify the object.
    """
    key: UserTypeFeature_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserTypeFeature_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserTypeFeature_Data!
  ): UserTypeFeature_KeyOutput @fdc_generated(from: "UserTypeFeature", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `WorkLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `WorkLog` or `null` if not found.
  """
  workLog_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: WorkLog_Data!
  ): WorkLog_KeyOutput @fdc_generated(from: "WorkLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update `ColorScheme` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  colorScheme_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ColorScheme_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ColorScheme_Data!
  ): Int! @fdc_generated(from: "ColorScheme", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Feature` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  feature_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Feature_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Feature_Data!
  ): Int! @fdc_generated(from: "Feature", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Team` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  team_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Team_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Team_Data!
  ): Int! @fdc_generated(from: "Team", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `TeamMember` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  teamMember_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: TeamMember_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: TeamMember_Data!
  ): Int! @fdc_generated(from: "TeamMember", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Theme` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  theme_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Theme_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Theme_Data!
  ): Int! @fdc_generated(from: "Theme", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Ticket` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  ticket_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Ticket_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Ticket_Data!
  ): Int! @fdc_generated(from: "Ticket", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `TimeEntry` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  timeEntry_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: TimeEntry_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: TimeEntry_Data!
  ): Int! @fdc_generated(from: "TimeEntry", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserType` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userType_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserType_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserType_Data!
  ): Int! @fdc_generated(from: "UserType", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserTypeFeature` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userTypeFeature_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserTypeFeature_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserTypeFeature_Data!
  ): Int! @fdc_generated(from: "UserTypeFeature", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `WorkLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  workLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: WorkLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: WorkLog_Data!
  ): Int! @fdc_generated(from: "WorkLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `ColorScheme` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  colorScheme_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ColorScheme_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ColorScheme_FirstRow
  ): ColorScheme_KeyOutput @fdc_generated(from: "ColorScheme", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Feature` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  feature_delete(
    """
    The key used to identify the object.
    """
    key: Feature_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Feature_FirstRow
  ): Feature_KeyOutput @fdc_generated(from: "Feature", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Team` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  team_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Team_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Team_FirstRow
  ): Team_KeyOutput @fdc_generated(from: "Team", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `TeamMember` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  teamMember_delete(
    """
    The key used to identify the object.
    """
    key: TeamMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TeamMember_FirstRow
  ): TeamMember_KeyOutput @fdc_generated(from: "TeamMember", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Theme` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  theme_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Theme_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Theme_FirstRow
  ): Theme_KeyOutput @fdc_generated(from: "Theme", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Ticket` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  ticket_delete(
    """
    The key used to identify the object.
    """
    key: Ticket_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Ticket_FirstRow
  ): Ticket_KeyOutput @fdc_generated(from: "Ticket", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `TimeEntry` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  timeEntry_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TimeEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TimeEntry_FirstRow
  ): TimeEntry_KeyOutput @fdc_generated(from: "TimeEntry", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserType` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userType_delete(
    """
    The key used to identify the object.
    """
    key: UserType_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserType_FirstRow
  ): UserType_KeyOutput @fdc_generated(from: "UserType", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserTypeFeature` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userTypeFeature_delete(
    """
    The key used to identify the object.
    """
    key: UserTypeFeature_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserTypeFeature_FirstRow
  ): UserTypeFeature_KeyOutput @fdc_generated(from: "UserTypeFeature", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `WorkLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  workLog_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkLog_FirstRow
  ): WorkLog_KeyOutput @fdc_generated(from: "WorkLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete `ColorScheme` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  colorScheme_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ColorScheme_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ColorScheme", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Feature` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  feature_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Feature_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Feature", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Team` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  team_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Team_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Team", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `TeamMember` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  teamMember_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: TeamMember_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "TeamMember", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Theme` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  theme_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Theme_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Theme", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Ticket` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  ticket_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Ticket_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Ticket", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `TimeEntry` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  timeEntry_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: TimeEntry_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "TimeEntry", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserType` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userType_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserType_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserType", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserTypeFeature` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userTypeFeature_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserTypeFeature_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserTypeFeature", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `WorkLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  workLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: WorkLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "WorkLog", purpose: DELETE_MULTIPLE)
}
