extend type Mutation {
  """
  ✨ Insert a single `TimeEntry` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  timeEntry_insert(
    """
    Data object to insert into the table.
    """
    data: TimeEntry_Data!
  ): TimeEntry_KeyOutput! @fdc_generated(from: "TimeEntry", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `WorkLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workLog_insert(
    """
    Data object to insert into the table.
    """
    data: WorkLog_Data!
  ): WorkLog_KeyOutput! @fdc_generated(from: "WorkLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert `TimeEntry` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  timeEntry_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [TimeEntry_Data!]!
  ): [TimeEntry_KeyOutput!]! @fdc_generated(from: "TimeEntry", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `WorkLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [WorkLog_Data!]!
  ): [WorkLog_KeyOutput!]! @fdc_generated(from: "WorkLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `TimeEntry` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TimeEntry`.
  """
  timeEntry_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: TimeEntry_Data!
  ): TimeEntry_KeyOutput! @fdc_generated(from: "TimeEntry", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `WorkLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorkLog`.
  """
  workLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: WorkLog_Data!
  ): WorkLog_KeyOutput! @fdc_generated(from: "WorkLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `TimeEntry` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TimeEntry`.
  """
  timeEntry_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [TimeEntry_Data!]!
  ): [TimeEntry_KeyOutput!]! @fdc_generated(from: "TimeEntry", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `WorkLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorkLog`.
  """
  workLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [WorkLog_Data!]!
  ): [WorkLog_KeyOutput!]! @fdc_generated(from: "WorkLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `TimeEntry` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `TimeEntry` or `null` if not found.
  """
  timeEntry_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TimeEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TimeEntry_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: TimeEntry_Data!
  ): TimeEntry_KeyOutput @fdc_generated(from: "TimeEntry", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `WorkLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `WorkLog` or `null` if not found.
  """
  workLog_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: WorkLog_Data!
  ): WorkLog_KeyOutput @fdc_generated(from: "WorkLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update `TimeEntry` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  timeEntry_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: TimeEntry_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: TimeEntry_Data!
  ): Int! @fdc_generated(from: "TimeEntry", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `WorkLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  workLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: WorkLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: WorkLog_Data!
  ): Int! @fdc_generated(from: "WorkLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `TimeEntry` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  timeEntry_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TimeEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TimeEntry_FirstRow
  ): TimeEntry_KeyOutput @fdc_generated(from: "TimeEntry", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `WorkLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  workLog_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkLog_FirstRow
  ): WorkLog_KeyOutput @fdc_generated(from: "WorkLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete `TimeEntry` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  timeEntry_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: TimeEntry_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "TimeEntry", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `WorkLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  workLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: WorkLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "WorkLog", purpose: DELETE_MULTIPLE)
}
