extend type Query {
  """
  ✨ Look up a single `ColorScheme` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  colorScheme(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ColorScheme_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ColorScheme_FirstRow
  ): ColorScheme @fdc_generated(from: "ColorScheme", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Feature` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  feature(
    """
    The key used to identify the object.
    """
    key: Feature_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Feature_FirstRow
  ): Feature @fdc_generated(from: "Feature", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Team` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  team(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Team_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Team_FirstRow
  ): Team @fdc_generated(from: "Team", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TeamMember` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  teamMember(
    """
    The key used to identify the object.
    """
    key: TeamMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TeamMember_FirstRow
  ): TeamMember @fdc_generated(from: "TeamMember", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Theme` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  theme(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Theme_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Theme_FirstRow
  ): Theme @fdc_generated(from: "Theme", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Ticket` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  ticket(
    """
    The key used to identify the object.
    """
    key: Ticket_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Ticket_FirstRow
  ): Ticket @fdc_generated(from: "Ticket", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TimeEntry` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  timeEntry(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TimeEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TimeEntry_FirstRow
  ): TimeEntry @fdc_generated(from: "TimeEntry", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UserType` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  userType(
    """
    The key used to identify the object.
    """
    key: UserType_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserType_FirstRow
  ): UserType @fdc_generated(from: "UserType", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UserTypeFeature` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  userTypeFeature(
    """
    The key used to identify the object.
    """
    key: UserTypeFeature_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserTypeFeature_FirstRow
  ): UserTypeFeature @fdc_generated(from: "UserTypeFeature", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `WorkLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  workLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkLog_FirstRow
  ): WorkLog @fdc_generated(from: "WorkLog", purpose: QUERY_SINGLE)
  """
  ✨ List `ColorScheme` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  colorSchemes(
    """
    Filter condition to narrow down the query results.
    """
    where: ColorScheme_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ColorScheme_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ColorScheme_Having
  ): [ColorScheme!]! @fdc_generated(from: "ColorScheme", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Feature` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  features(
    """
    Filter condition to narrow down the query results.
    """
    where: Feature_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Feature_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Feature_Having
  ): [Feature!]! @fdc_generated(from: "Feature", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Team` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  teams(
    """
    Filter condition to narrow down the query results.
    """
    where: Team_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Team_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Team_Having
  ): [Team!]! @fdc_generated(from: "Team", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TeamMember` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  teamMembers(
    """
    Filter condition to narrow down the query results.
    """
    where: TeamMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TeamMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TeamMember_Having
  ): [TeamMember!]! @fdc_generated(from: "TeamMember", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Theme` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  themes(
    """
    Filter condition to narrow down the query results.
    """
    where: Theme_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Theme_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Theme_Having
  ): [Theme!]! @fdc_generated(from: "Theme", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Ticket` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tickets(
    """
    Filter condition to narrow down the query results.
    """
    where: Ticket_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Ticket_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Ticket_Having
  ): [Ticket!]! @fdc_generated(from: "Ticket", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TimeEntry` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  timeEntries(
    """
    Filter condition to narrow down the query results.
    """
    where: TimeEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TimeEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TimeEntry_Having
  ): [TimeEntry!]! @fdc_generated(from: "TimeEntry", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UserType` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  userTypes(
    """
    Filter condition to narrow down the query results.
    """
    where: UserType_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserType_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserType_Having
  ): [UserType!]! @fdc_generated(from: "UserType", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UserTypeFeature` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  userTypeFeatures(
    """
    Filter condition to narrow down the query results.
    """
    where: UserTypeFeature_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserTypeFeature_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserTypeFeature_Having
  ): [UserTypeFeature!]! @fdc_generated(from: "UserTypeFeature", purpose: QUERY_MULTIPLE)
  """
  ✨ List `WorkLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  workLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: WorkLog_Having
  ): [WorkLog!]! @fdc_generated(from: "WorkLog", purpose: QUERY_MULTIPLE)
}
