extend type Query {
  """
  ✨ Look up a single `TimeEntry` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  timeEntry(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TimeEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TimeEntry_FirstRow
  ): TimeEntry @fdc_generated(from: "TimeEntry", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `WorkLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  workLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkLog_FirstRow
  ): WorkLog @fdc_generated(from: "WorkLog", purpose: QUERY_SINGLE)
  """
  ✨ List `TimeEntry` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  timeEntries(
    """
    Filter condition to narrow down the query results.
    """
    where: TimeEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TimeEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TimeEntry_Having
  ): [TimeEntry!]! @fdc_generated(from: "TimeEntry", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `WorkLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  workLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: WorkLog_Having
  ): [WorkLog!]! @fdc_generated(from: "WorkLog", purpose: QUERY_MULTIPLE)
}
