extend type ColorScheme {
  """
  ✨ List `Theme` objects in a one-to-many relationship (where `Theme`.`colorScheme` is this object).
  """
  themes_on_colorScheme(
    """
    Filter condition to narrow down the query results.
    """
    where: Theme_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Theme_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Theme_Having
  ): [Theme!]! @fdc_generated(from: "Theme.colorScheme", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `User` objects in a one-to-many relationship (where `User`.`colorScheme` is this object).
  """
  users_on_colorScheme(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User.colorScheme", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "ColorScheme", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `ColorScheme` table.
  """
  _count: Int! @fdc_generated(from: "ColorScheme.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ColorScheme` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ColorScheme.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ColorScheme` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ColorScheme.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ColorScheme` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ColorScheme.name", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `ColorScheme` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "ColorScheme.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `ColorScheme` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "ColorScheme.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "ColorScheme.id", purpose: ENTITY_ID)
}
extend type Feature {
  """
  ✨ List `UserTypeFeature` objects in a one-to-many relationship (where `UserTypeFeature`.`feature` is this object).
  """
  userTypeFeatures_on_feature(
    """
    Filter condition to narrow down the query results.
    """
    where: UserTypeFeature_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserTypeFeature_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserTypeFeature_Having
  ): [UserTypeFeature!]! @fdc_generated(from: "UserTypeFeature.feature", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `UserType` objects using `UserTypeFeature` as the join table (a `UserTypeFeature` object exists where its `feature` is this and its `userType` is that).
  """
  userTypes_via_UserTypeFeature(
    """
    Filter condition to narrow down the query results.
    """
    where: UserTypeFeature_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserTypeFeature_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserTypeFeature_Having
  ): [UserType!]! @fdc_generated(from: "UserTypeFeature", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Feature", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Feature` table.
  """
  _count: Int! @fdc_generated(from: "Feature.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Feature` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Feature.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Feature` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Feature.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Feature` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Feature.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Feature` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Feature.name", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Feature` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Feature.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Feature` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Feature.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Feature.name", purpose: ENTITY_ID)
}
extend type Team {
  """
  ✨ List `TeamMember` objects in a one-to-many relationship (where `TeamMember`.`team` is this object).
  """
  teamMembers_on_team(
    """
    Filter condition to narrow down the query results.
    """
    where: TeamMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TeamMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TeamMember_Having
  ): [TeamMember!]! @fdc_generated(from: "TeamMember.team", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `User` objects using `TeamMember` as the join table (a `TeamMember` object exists where its `team` is this and its `user` is that).
  """
  users_via_TeamMember(
    """
    Filter condition to narrow down the query results.
    """
    where: TeamMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TeamMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TeamMember_Having
  ): [User!]! @fdc_generated(from: "TeamMember", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Team", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Team` table.
  """
  _count: Int! @fdc_generated(from: "Team.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Team` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Team.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Team` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Team.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Team` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Team.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Team` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Team.name", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Team` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Team.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Team` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Team.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Team.id", purpose: ENTITY_ID)
}
extend type TeamMember {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "TeamMember", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `TeamMember` table.
  """
  _count: Int! @fdc_generated(from: "TeamMember.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TeamMember` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TeamMember.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TeamMember` table where the `teamId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  teamId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TeamMember.teamId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TeamMember` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TeamMember.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `TeamMember` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "TeamMember.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `TeamMember` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "TeamMember.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "TeamMember.teamId,userId", purpose: ENTITY_ID)
}
extend type Theme {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Theme", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Theme` table.
  """
  _count: Int! @fdc_generated(from: "Theme.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `accentForeground` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  accentForeground_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.accentForeground", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `accent` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  accent_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.accent", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `background` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  background_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.background", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `border` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  border_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.border", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `colorSchemeId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  colorSchemeId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.colorSchemeId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `defaultForeground` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  defaultForeground_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.defaultForeground", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `default` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  default_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.default", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `foreground` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  foreground_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.foreground", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `isDark` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isDark_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.isDark", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `muted` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  muted_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.muted", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `overlayForeground` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  overlayForeground_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.overlayForeground", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `overlay` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  overlay_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.overlay", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `separator` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  separator_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.separator", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `surfaceForeground` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  surfaceForeground_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.surfaceForeground", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Theme` table where the `surface` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  surface_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Theme.surface", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Theme` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Theme.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Theme` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Theme.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Theme.id", purpose: ENTITY_ID)
}
extend type Ticket {
  """
  ✨ List `TimeEntry` objects in a one-to-many relationship (where `TimeEntry`.`ticket` is this object).
  """
  timeEntries_on_ticket(
    """
    Filter condition to narrow down the query results.
    """
    where: TimeEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TimeEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TimeEntry_Having
  ): [TimeEntry!]! @fdc_generated(from: "TimeEntry.ticket", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Ticket", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Ticket` table.
  """
  _count: Int! @fdc_generated(from: "Ticket.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Ticket` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Ticket.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Ticket` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Ticket.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Ticket` table where the `office` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  office_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Ticket.office", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Ticket` table where the `ticketLink` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ticketLink_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Ticket.ticketLink", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Ticket` table where the `ticketNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ticketNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Ticket.ticketNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Ticket` table where the `ticketTitle` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ticketTitle_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Ticket.ticketTitle", purpose: QUERY_COUNT)
  """
  ✨ Sum the `ticketNumber` field in the `Ticket` table.
  """
  ticketNumber_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Ticket.ticketNumber", purpose: QUERY_SUM)
  """
  ✨ Average the `ticketNumber` field in the `Ticket` table.
  """
  ticketNumber_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Ticket.ticketNumber", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Ticket` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Ticket.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `ticketNumber` field in the `Ticket` table.
  """
  ticketNumber_min: Int @fdc_generated(from: "Ticket.ticketNumber", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Ticket` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Ticket.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `ticketNumber` field in the `Ticket` table.
  """
  ticketNumber_max: Int @fdc_generated(from: "Ticket.ticketNumber", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Ticket.ticketNumber", purpose: ENTITY_ID)
}
extend type TimeEntry {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "TimeEntry", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `TimeEntry` table.
  """
  _count: Int! @fdc_generated(from: "TimeEntry.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TimeEntry` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TimeEntry.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TimeEntry` table where the `date` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  date_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TimeEntry.date", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TimeEntry` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TimeEntry.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TimeEntry` table where the `endTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  endTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TimeEntry.endTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TimeEntry` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TimeEntry.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TimeEntry` table where the `officeNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  officeNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TimeEntry.officeNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TimeEntry` table where the `startTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TimeEntry.startTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TimeEntry` table where the `ticketTicketNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ticketTicketNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TimeEntry.ticketTicketNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TimeEntry` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TimeEntry.userId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TimeEntry` table where the `workLogId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  workLogId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TimeEntry.workLogId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `ticketTicketNumber` field in the `TimeEntry` table.
  """
  ticketTicketNumber_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "TimeEntry.ticketTicketNumber", purpose: QUERY_SUM)
  """
  ✨ Average the `ticketTicketNumber` field in the `TimeEntry` table.
  """
  ticketTicketNumber_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "TimeEntry.ticketTicketNumber", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `TimeEntry` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "TimeEntry.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `date` field in the `TimeEntry` table.
  """
  date_min: Date @fdc_generated(from: "TimeEntry.date", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `endTime` field in the `TimeEntry` table.
  """
  endTime_min: Timestamp @fdc_generated(from: "TimeEntry.endTime", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startTime` field in the `TimeEntry` table.
  """
  startTime_min: Timestamp @fdc_generated(from: "TimeEntry.startTime", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `ticketTicketNumber` field in the `TimeEntry` table.
  """
  ticketTicketNumber_min: Int @fdc_generated(from: "TimeEntry.ticketTicketNumber", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `TimeEntry` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "TimeEntry.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `date` field in the `TimeEntry` table.
  """
  date_max: Date @fdc_generated(from: "TimeEntry.date", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `endTime` field in the `TimeEntry` table.
  """
  endTime_max: Timestamp @fdc_generated(from: "TimeEntry.endTime", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startTime` field in the `TimeEntry` table.
  """
  startTime_max: Timestamp @fdc_generated(from: "TimeEntry.startTime", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `ticketTicketNumber` field in the `TimeEntry` table.
  """
  ticketTicketNumber_max: Int @fdc_generated(from: "TimeEntry.ticketTicketNumber", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "TimeEntry.id", purpose: ENTITY_ID)
}
extend type User {
  """
  ✨ List `TeamMember` objects in a one-to-many relationship (where `TeamMember`.`user` is this object).
  """
  teamMembers_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: TeamMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TeamMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TeamMember_Having
  ): [TeamMember!]! @fdc_generated(from: "TeamMember.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `TimeEntry` objects in a one-to-many relationship (where `TimeEntry`.`user` is this object).
  """
  timeEntries_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: TimeEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TimeEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TimeEntry_Having
  ): [TimeEntry!]! @fdc_generated(from: "TimeEntry.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `WorkLog` objects in a one-to-many relationship (where `WorkLog`.`user` is this object).
  """
  workLogs_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: WorkLog_Having
  ): [WorkLog!]! @fdc_generated(from: "WorkLog.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Team` objects using `TeamMember` as the join table (a `TeamMember` object exists where its `user` is this and its `team` is that).
  """
  teams_via_TeamMember(
    """
    Filter condition to narrow down the query results.
    """
    where: TeamMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TeamMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TeamMember_Having
  ): [Team!]! @fdc_generated(from: "TeamMember", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `backgroundOpacity` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  backgroundOpacity_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.backgroundOpacity", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `bordersEnabled` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bordersEnabled_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.bordersEnabled", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `cardBlur` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  cardBlur_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.cardBlur", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `cardOpacity` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  cardOpacity_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.cardOpacity", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `colorSchemeId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  colorSchemeId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.colorSchemeId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `externalTicketLinkTemplate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  externalTicketLinkTemplate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.externalTicketLinkTemplate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `googleUid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  googleUid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.googleUid", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `performanceMode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  performanceMode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.performanceMode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `userTypeName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userTypeName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.userTypeName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `username` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  username_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.username", purpose: QUERY_COUNT)
  """
  ✨ Sum the `backgroundOpacity` field in the `User` table.
  """
  backgroundOpacity_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "User.backgroundOpacity", purpose: QUERY_SUM)
  """
  ✨ Sum the `cardBlur` field in the `User` table.
  """
  cardBlur_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "User.cardBlur", purpose: QUERY_SUM)
  """
  ✨ Sum the `cardOpacity` field in the `User` table.
  """
  cardOpacity_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "User.cardOpacity", purpose: QUERY_SUM)
  """
  ✨ Average the `backgroundOpacity` field in the `User` table.
  """
  backgroundOpacity_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "User.backgroundOpacity", purpose: QUERY_AVG)
  """
  ✨ Average the `cardBlur` field in the `User` table.
  """
  cardBlur_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "User.cardBlur", purpose: QUERY_AVG)
  """
  ✨ Average the `cardOpacity` field in the `User` table.
  """
  cardOpacity_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "User.cardOpacity", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `backgroundOpacity` field in the `User` table.
  """
  backgroundOpacity_min: Int @fdc_generated(from: "User.backgroundOpacity", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `cardBlur` field in the `User` table.
  """
  cardBlur_min: Int @fdc_generated(from: "User.cardBlur", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `cardOpacity` field in the `User` table.
  """
  cardOpacity_min: Int @fdc_generated(from: "User.cardOpacity", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `backgroundOpacity` field in the `User` table.
  """
  backgroundOpacity_max: Int @fdc_generated(from: "User.backgroundOpacity", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `cardBlur` field in the `User` table.
  """
  cardBlur_max: Int @fdc_generated(from: "User.cardBlur", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `cardOpacity` field in the `User` table.
  """
  cardOpacity_max: Int @fdc_generated(from: "User.cardOpacity", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: ENTITY_ID)
}
extend type UserType {
  """
  ✨ List `User` objects in a one-to-many relationship (where `User`.`userType` is this object).
  """
  users_on_userType(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User.userType", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `UserTypeFeature` objects in a one-to-many relationship (where `UserTypeFeature`.`userType` is this object).
  """
  userTypeFeatures_on_userType(
    """
    Filter condition to narrow down the query results.
    """
    where: UserTypeFeature_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserTypeFeature_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserTypeFeature_Having
  ): [UserTypeFeature!]! @fdc_generated(from: "UserTypeFeature.userType", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Feature` objects using `UserTypeFeature` as the join table (a `UserTypeFeature` object exists where its `userType` is this and its `feature` is that).
  """
  features_via_UserTypeFeature(
    """
    Filter condition to narrow down the query results.
    """
    where: UserTypeFeature_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserTypeFeature_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserTypeFeature_Having
  ): [Feature!]! @fdc_generated(from: "UserTypeFeature", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "UserType", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `UserType` table.
  """
  _count: Int! @fdc_generated(from: "UserType.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserType` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserType.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserType` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserType.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserType` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserType.name", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `UserType` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "UserType.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `UserType` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "UserType.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "UserType.name", purpose: ENTITY_ID)
}
extend type UserTypeFeature {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "UserTypeFeature", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `UserTypeFeature` table.
  """
  _count: Int! @fdc_generated(from: "UserTypeFeature.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserTypeFeature` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserTypeFeature.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserTypeFeature` table where the `featureName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  featureName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserTypeFeature.featureName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserTypeFeature` table where the `userTypeName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userTypeName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserTypeFeature.userTypeName", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `UserTypeFeature` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "UserTypeFeature.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `UserTypeFeature` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "UserTypeFeature.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "UserTypeFeature.userTypeName,featureName", purpose: ENTITY_ID)
}
extend type WorkLog {
  """
  ✨ List `TimeEntry` objects in a one-to-many relationship (where `TimeEntry`.`workLog` is this object).
  """
  timeEntries_on_workLog(
    """
    Filter condition to narrow down the query results.
    """
    where: TimeEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TimeEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TimeEntry_Having
  ): [TimeEntry!]! @fdc_generated(from: "TimeEntry.workLog", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "WorkLog", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `WorkLog` table.
  """
  _count: Int! @fdc_generated(from: "WorkLog.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WorkLog` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WorkLog.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WorkLog` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WorkLog.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WorkLog` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WorkLog.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WorkLog` table where the `isDeleted` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isDeleted_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WorkLog.isDeleted", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WorkLog` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WorkLog.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WorkLog` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WorkLog.userId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WorkLog` table where the `workLogDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  workLogDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WorkLog.workLogDate", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `WorkLog` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "WorkLog.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `workLogDate` field in the `WorkLog` table.
  """
  workLogDate_min: Timestamp @fdc_generated(from: "WorkLog.workLogDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `WorkLog` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "WorkLog.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `workLogDate` field in the `WorkLog` table.
  """
  workLogDate_max: Timestamp @fdc_generated(from: "WorkLog.workLogDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "WorkLog.id", purpose: ENTITY_ID)
}
